### ISSUE TITLE
Unable to define NotificationPolicy with timeRestrictions

### ISSUE THREAD

**Issue by fronti90** [pulumi/pulumi-opsgenie#56]
### What happened?

I am trying to define a NotificationPolicy with timeRestrictions, but there seems to be an issue with NotificationPolicy.TimeRestrictions[0].Restriction[0].EndDay and NotificationPolicy.TimeRestrictions[0].Restriction[0].StartDay.

### Steps to reproduce

```
new opsgenie.NotificationPolicy(
			notificationName,
			{
				name: notificationName,
				policyDescription: 'managed by pulumi',
				teamId: inputs.teamId,
				enabled: true,
                                timeRestrictions: [
					{
						restriction: [
							{
								startHour: 1,
								startMin: 0,
								endHour: 7,
								endMin: 0,
							},
						],
						type: 'time-of-day',
					},
				],
				delayActions: [
					{
						delayOption: 'next-time',
						untilHour: 7,
						untilMinute: 1,
					},
				],
				filters: [{}],
			},
```

This results in:

```
$pulumi preview --diff                                                                                        
Previewing update (platform.prod):
INFO[2022-07-18T14:01:32.943432167+02:00] Client is configured with ApiUrl: api.eu.opsgenie.com, LogLevel: info, RetryMaxCount: 10

  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:platform.prod::xxx::pulumi:pulumi:Stack::xxx-platform.prod]
error: Running program '/home/xxx/git/platform' failed with an unhandled exception:
TSError: ⨯ Unable to compile TypeScript:
src/opsgenie/notification-policy.ts(14,5): error TS2322: Type '{ restriction: { startHour: number; startMin: number; endHour: number; endMin: number; }[]; type: string; }[]' is not assignable to type 'Input<NotificationPolicyTimeRestriction>[] | Promise<Input<NotificationPolicyTimeRestriction>[]> | OutputInstance<...> | undefined'.
  Type '{ restriction: { startHour: number; startMin: number; endHour: number; endMin: number; }[]; type: string; }[]' is not assignable to type 'Input<NotificationPolicyTimeRestriction>[]'.
    Type '{ restriction: { startHour: number; startMin: number; endHour: number; endMin: number; }[]; type: string; }' is not assignable to type 'Input<NotificationPolicyTimeRestriction>'.
      Type '{ restriction: { startHour: number; startMin: number; endHour: number; endMin: number; }[]; type: string; }' is not assignable to type 'NotificationPolicyTimeRestriction'.
        Types of property 'restriction' are incompatible.
          Type '{ startHour: number; startMin: number; endHour: number; endMin: number; }[]' is not assignable to type 'Input<NotificationPolicyTimeRestrictionRestriction>[] | Promise<Input<NotificationPolicyTimeRestrictionRestriction>[]> | OutputInstance<...> | undefined'.
            Type '{ startHour: number; startMin: number; endHour: number; endMin: number; }[]' is not assignable to type 'Input<NotificationPolicyTimeRestrictionRestriction>[]'.
              Type '{ startHour: number; startMin: number; endHour: number; endMin: number; }' is not assignable to type 'Input<NotificationPolicyTimeRestrictionRestriction>'.
                Type '{ startHour: number; startMin: number; endHour: number; endMin: number; }' is missing the following properties from type 'NotificationPolicyTimeRestrictionRestriction': endDay, startDay

    at createTSError (/home/xxx/git/platform/node_modules/@pulumi/pulumi/node_modules/ts-node/src/index.ts:261:12)
    at getOutput (/home/xxx/git/platform/node_modules/@pulumi/pulumi/node_modules/ts-node/src/index.ts:367:40)
    at Object.compile (/home/xxx/git/platform/node_modules/@pulumi/pulumi/node_modules/ts-node/src/index.ts:558:11)
    at Module.m._compile (/home/xxx/git/platform/node_modules/@pulumi/pulumi/node_modules/ts-node/src/index.ts:439:43)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Object.require.extensions.<computed> [as .ts] (/home/xxx/git/platform/node_modules/@pulumi/pulumi/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Function.Module._load (node:internal/modules/cjs/loader:834:12)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    --outputs:--
```

Adding startDay and endDay as additional parameters throws this error:

```
error: opsgenie:index/notificationPolicy:NotificationPolicy resource 'Delay policy' has a problem: Invalid or unknown key. Examine values at 'NotificationPolicy.TimeRestrictions[0].Restriction[0].StartDay'.
error: opsgenie:index/notificationPolicy:NotificationPolicy resource 'Delay policy' has a problem: Invalid or unknown key. Examine values at 'NotificationPolicy.TimeRestrictions[0].Restriction[0].EndDay'.
```

### Expected Behavior

Notification Policy is created successfully with a time restriction set of type time-of-day.

### Actual Behavior

Notification Policy isn't created at all (see Steps to reproduce)

### Versions used

CLI
Version      3.34.1
Go Version   go1.18.3
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.10.0
gitlab      4.7.1
kubernetes  3.20.0
nodejs      unknown
opsgenie    1.1.6
random      4.8.0
tls         4.6.0

Host
OS       arch
Version  21.3.3
Arch     x86_64

### Additional context

Seems to be a similar issue as in https://github.com/pulumi/pulumi-opsgenie/issues/17, https://github.com/pulumi/pulumi-opsgenie/issues/51 and https://github.com/pulumi/pulumi-opsgenie/issues/52
Creating it with type 'weekday-and-time-of-day' and 'startDay'/'endDay' works without issues, which can be used as a workaround but produces lots of addtional code.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
update

**Comment by guineveresaenger** [comment]
Hi @fronti90 - you should be able to use `NotificationPolicyTimeRestrictionRestrictionList` to include startDay and endDay.

[Release notes here](https://github.com/pulumi/pulumi-opsgenie/releases/tag/v1.1.7) - let us know if you need further assistance.

Thanks to you, we could find and fix a bug that we may encounter elsewhere, and we really appreciate you reporting it!

**Comment by fronti90** [comment]
Thanks @guineveresaenger for the quick fix, much appreciated!
